### ISSUE TITLE
No Screen Shot yet

### ISSUE THREAD

**Issue by mmohamedrashik** [ribomation/DroidAtScreen1#21]
Recieved the following error while connecting with ET701 TAB
Recieved the same error with version 1.2
![issue](https://cloud.githubusercontent.com/assets/6525001/8889419/295f1c62-328f-11e5-8031-c33c66b6d44e.jpg)

**Comment by ribomation** [comment]
ADB believes your device is offline. Try reconnecting the USB. Try restarting ADB.
Also, ensure that you have Developer Mode enabled on the device and USB Debugging enabled.
More info at http://droid-at-screen.org/installation.html

**Comment by mmohamedrashik** [comment]
Everything has been checked ! But Still facing the same issue with this particular device (ET701). 
![issues2](https://cloud.githubusercontent.com/assets/6525001/8889531/a2cee93a-3292-11e5-8d78-e4005f6a08b4.png)

**Comment by ribomation** [comment]
This is a problem with the connection of ADB and your device. Try running DDMS, to reveal any problems. You can find it in $ANDROID_SDK/tools/ddms.bat
DDMS and other tools are all relying on the ADM daemon to provide a connection to a device.

**Comment by mmohamedrashik** [comment]
Device successfully connected with DDMS. But the same issue occurs in DDMS screen capture option
![issue3](https://cloud.githubusercontent.com/assets/6525001/8892245/c4b830a8-3303-11e5-9dca-71f858483fa2.jpg)
.

**Comment by ribomation** [comment]
droid@screen is using the same API as DDMS and take screenshots in a rapid pace.
When you can take a screenshot in DDMS, you will also be able to view your device in droid@screen.
