### ISSUE TITLE
Keyboard input

### ISSUE THREAD

**Issue by orgicus** [ribomation/DroidAtScreen1#31]
The application is super-useful as it is! 
Thank you for sharing that freely and open source.

I was wondering, is keyboard/typing is supported ?
If so, how can test/enable that ?
Otherwise, any plans for such a feature ? :)

Thank you,
George

**Comment by niknah** [comment]
Try this one...
https://github.com/niknah/AndroidViaWeb

**Comment by alamari** [comment]
although it seems in ver 1.2 keyboard input is supported, still it does not seem to work. any specific setup is required ?
=> niknah ---- can you please explain how to use the tool? is it in addition to DroidAtScreen ? any aditional input is appreciate.

**Comment by niknah** [comment]
No, it's a separate tool but it lets you enter things via the keyboard.  There's install instructions on the page.  You will need to plug in the device into the usb of a PC.  Tell me if you don't understand.
